# Generated by Django 3.0.4 on 2022-01-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(default='', max_length=100)),
                ('user', models.CharField(default='', max_length=100)),
                ('filename', models.CharField(default='', max_length=255)),
                ('request_id', models.CharField(default='', max_length=100)),
                ('created_at', models.DateField(auto_now=True)),
                ('transfer_type', models.CharField(choices=[('download', 'Download transfer'), ('upload', 'Upload transfer')], default='', max_length=100)),
            ],
        ),
    ]
