# Generated by Django 3.0.4 on 2022-01-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatransfer',
            name='access',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='datatransfer',
            name='task_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='datatransfer',
            name='zone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
