- include: install_debian.yml
  when: ansible_os_family == 'Debian'

- include: install_redhat.yml
  when: ansible_os_family == 'RedHat'

- include: deploy_venv.yml

- include: db_migration.yml
  tags:
    - migrate